
/***************************************************************************//**
 * Copyright (c) 2021 RKDAW Enterprises and Ralph Williamson,
 * <rkdawenterprises.ddns.net, rkdawenterprises@gmail.com>. All rights reserved.
 * This program, and the accompanying materials, are provided under the terms
 * of the Eclipse Public License v2.0 (the "License"). You may not use this
 * file except in compliance with the License. You may obtain a copy of the
 * License at "https://www.eclipse.org/legal/epl-2.0".
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions, warranties,
 * and limitations under the License.
 ******************************************************************************/

package net.ddns.rkdawenterprises.brief4eclipse;

import org.eclipse.osgi.util.NLS;

/**
 * Should not modify. Generated by eclipse localization functionality.
 */
public class Messages extends NLS
{
    private static final String BUNDLE_NAME = "net.ddns.rkdawenterprises.brief4eclipse.messages"; //$NON-NLS-1$

    public static String abstract_table_dialog_1;

    public static String abstract_table_dialog_2;

    public static String bookmark_dialog_1;

    public static String bookmark_dialog_2;

    public static String bookmark_dialog_3;

    public static String bookmarks_support_18;

    public static String bookmarks_support_19;

    public static String bookmarks_support_22;

    public static String brief_for_eclipse_13;

    public static String brief_for_eclipse_14;

    public static String brief_for_eclipse_15;

    public static String brief_for_eclipse_16;

    public static String brief_for_eclipse_17;

    public static String command_dialog_command_prompt_format;

    public static String command_dialog_command_prompt_initial_instructions;

    public static String command_dialog_mod1_plus_key;

    public static String command_dialog_mod2_plus_key;

    public static String command_dialog_mod3_plus_key;

    public static String command_dialog_repeat_command_key_binding;

    public static String goto_line_number_dialog_prompt_format;

    public static String jump_bookmark_number_dialog_prompt_format;

    public static String scrap_dialog_0;

    public static String scrap_dialog_1;

    public static String scrap_dialog_2;

    public static String scrap_dialog_3;

    public static String scrap_support_9;

    public static String text_editor_proxy_0;

    public static String text_editor_proxy_48;

    public static String text_editor_proxy_49;

    public static String text_editor_proxy_1;

    public static String text_editor_proxy_12;

    public static String text_editor_proxy_13;

    public static String text_editor_proxy_14;

    public static String text_editor_proxy_15;

    public static String text_editor_proxy_17;

    public static String text_editor_proxy_18;

    public static String text_editor_proxy_19;

    public static String text_editor_proxy_20;

    public static String text_editor_proxy_24;

    public static String text_editor_proxy_42;

    public static String text_editor_proxy_43;

    public static String text_editor_proxy_44;

    public static String text_editor_proxy_46;

    public static String text_editor_proxy_47;

    static
    {
        NLS.initializeMessages( BUNDLE_NAME,
                                Messages.class );
    }

    private Messages() {}
}
